name: PadChest
root: data/raw/PadChest
split_csv: data/processed/splits/padchest_splits.csv
img_size: [320, 320]
normalize_mean: [0.485, 0.456, 0.406]
normalize_std:  [0.229, 0.224, 0.225]
multi_label: true
harmonize_to: NIH_CXR14
harmonization_table: data/processed/padchest_to_nih14.csv
